import type { SettingsSectionDefinition } from './settingsSchemaBase';
import { field } from './settingsSchemaBase';
import {
  COST,
  COUNT,
  DEGREES,
  DEGREES_PER_SECOND,
  ITERATIONS,
  KILOMETERS_PER_HOUR,
  METERS,
  METERS_PER_SECOND_SQUARED,
  RATIO,
  SCALE,
  STEPS,
  THRESHOLD,
} from './settingsUnits';

export const CONTROLLER_SETTINGS_SECTIONS: SettingsSectionDefinition[] = [
  {
    title: 'Vehicle geometry',
    description: 'Vehicle dimensions, wheel layout, and collision shape parameters.',
    fields: [
      field(
        ['controller', 'carConfig', 'wheelBase'],
        'Wheel base',
        'Distance between rear and front axles.',
        0.1,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'length'],
        'Body length',
        'Vehicle body length used for drawing and collision.',
        0.1,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'width'],
        'Body width',
        'Vehicle body width used for drawing and collision.',
        0.1,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'backToWheel'],
        'Rear overhang',
        'Distance from rear axle to vehicle tail.',
        0.1,
        METERS,
        0,
      ),
      field(
        ['controller', 'carConfig', 'wheelLength'],
        'Wheel length',
        'Visualized wheel rectangle length.',
        0.05,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'wheelWidth'],
        'Wheel width',
        'Visualized wheel rectangle width.',
        0.05,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'wheelSpacing'],
        'Wheel spacing',
        'Track width used for the wheel visuals.',
        0.05,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'collisionPadding'],
        'Collision padding',
        'Extra safety padding around the vehicle body.',
        0.05,
        METERS,
        0,
      ),
      field(
        ['controller', 'carConfig', 'scanRadius'],
        'Scan radius',
        'Obstacle sensing radius around the vehicle.',
        0.5,
        METERS,
        0.001,
      ),
    ],
  },
  {
    title: 'Vehicle motion',
    description: 'Steering, speed, and acceleration limits for the car model.',
    fields: [
      field(
        ['controller', 'carConfig', 'targetMaxSteer'],
        'Target max steer',
        'Target steering angle limit.',
        1,
        DEGREES,
        0.001,
      ),
      field(['controller', 'carConfig', 'maxSteer'], 'Max steer', 'Absolute steering angle limit.', 1, DEGREES, 0.001),
      field(
        ['controller', 'carConfig', 'maxSteerSpeed'],
        'Max steer speed',
        'Maximum steering rate.',
        5,
        DEGREES_PER_SECOND,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'maxSpeed'],
        'Max speed',
        'Maximum forward speed.',
        1,
        KILOMETERS_PER_HOUR,
        0.001,
      ),
      field(['controller', 'carConfig', 'minSpeed'], 'Min speed', 'Maximum reverse speed.', 1, KILOMETERS_PER_HOUR),
      field(
        ['controller', 'carConfig', 'maxAccel'],
        'Max acceleration',
        'Maximum longitudinal acceleration.',
        0.5,
        METERS_PER_SECOND_SQUARED,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'maxCentripetalAccel'],
        'Max centripetal accel',
        'Maximum turning acceleration before clipping.',
        0.5,
        METERS_PER_SECOND_SQUARED,
        0.001,
      ),
      field(
        ['controller', 'carConfig', 'targetSpeed'],
        'Target speed',
        'Cruising speed used by the planner.',
        1,
        KILOMETERS_PER_HOUR,
      ),
    ],
  },
  {
    title: 'Hybrid A* planner',
    description: 'Search discretization and path cost tuning for the global planner.',
    fields: [
      field(
        ['controller', 'hybridAStarConfig', 'xyGridResolution'],
        'XY grid resolution',
        'Cell size of the planner grid.',
        0.1,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'yawGridResolution'],
        'Yaw grid resolution',
        'Heading discretization of the planner grid.',
        1,
        DEGREES,
        0.001,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'motionDistance'],
        'Motion distance',
        'Expansion length for each search step.',
        0.1,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'motionResolution'],
        'Motion resolution',
        'Sampling resolution along each search step.',
        0.05,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'numSteerCommands'],
        'Steer commands',
        'Number of steering choices per expansion.',
        1,
        COUNT,
        1,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'reedsSheppMaxDistance'],
        'Reeds-Shepp max distance',
        'Maximum analytic expansion distance.',
        0.5,
        METERS,
        0,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'switchDirectionCost'],
        'Direction switch cost',
        'Penalty for forward/reverse transitions.',
        0.5,
        COST,
        0,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'backwardsCost'],
        'Backwards cost',
        'Penalty for reverse motion.',
        0.25,
        COST,
        0,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'steerChangeCost'],
        'Steer change cost',
        'Penalty for changing steering between steps.',
        0.25,
        COST,
        0,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'steerCost'],
        'Steer cost',
        'Penalty for steering magnitude.',
        0.25,
        COST,
        0,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'heuristicDistanceCost'],
        'Heuristic distance cost',
        'Distance term weight in the heuristic.',
        0.25,
        COST,
        0,
      ),
      field(
        ['controller', 'hybridAStarConfig', 'heuristicYawCost'],
        'Heuristic yaw cost',
        'Heading term weight in the heuristic.',
        0.25,
        COST,
        0,
      ),
    ],
  },
  {
    title: 'MPC controller',
    description: 'Preview horizon, convergence controls, and tracking cost weights.',
    fields: [
      field(
        ['controller', 'mpcConfig', 'horizonLength'],
        'Horizon length',
        'Number of MPC steps in the preview horizon.',
        1,
        STEPS,
        1,
      ),
      field(
        ['controller', 'mpcConfig', 'maxIterations'],
        'Max iterations',
        'Maximum solver iterations per update.',
        1,
        ITERATIONS,
        1,
      ),
      field(
        ['controller', 'mpcConfig', 'duThreshold'],
        'DU threshold',
        'Convergence threshold for control updates.',
        0.01,
        THRESHOLD,
        0.001,
      ),
      field(
        ['controller', 'mpcConfig', 'accelCost'],
        'Acceleration cost',
        'Weight on acceleration magnitude.',
        0.001,
        COST,
        0,
      ),
      field(['controller', 'mpcConfig', 'steerCost'], 'Steer cost', 'Weight on steering magnitude.', 0.001, COST, 0),
      field(
        ['controller', 'mpcConfig', 'accelDeltaCost'],
        'Acceleration delta cost',
        'Weight on acceleration smoothness.',
        0.00001,
        COST,
        0,
      ),
      field(
        ['controller', 'mpcConfig', 'steerDeltaCost'],
        'Steer delta cost',
        'Weight on steering smoothness.',
        0.0001,
        COST,
        0,
      ),
      field(['controller', 'mpcConfig', 'xCost'], 'X cost', 'Weight on longitudinal tracking error.', 0.1, COST, 0),
      field(['controller', 'mpcConfig', 'yCost'], 'Y cost', 'Weight on lateral tracking error.', 0.1, COST, 0),
      field(
        ['controller', 'mpcConfig', 'velocityCost'],
        'Velocity cost',
        'Weight on speed tracking error.',
        0.01,
        COST,
        0,
      ),
      field(['controller', 'mpcConfig', 'yawCost'], 'Yaw cost', 'Weight on heading tracking error.', 0.1, COST, 0),
      field(
        ['controller', 'mpcConfig', 'terminalCostScale'],
        'Terminal cost scale',
        'Multiplier applied to the terminal state cost.',
        0.1,
        SCALE,
        0,
      ),
      field(
        ['controller', 'mpcConfig', 'desiredMaxAccelRatio'],
        'Desired max accel ratio',
        'Requested ratio of the configured max acceleration.',
        0.05,
        RATIO,
        0.001,
      ),
      field(
        ['controller', 'mpcConfig', 'minHorizonDistance'],
        'Min horizon distance',
        'Minimum forward distance covered by the MPC horizon.',
        0.05,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'mpcConfig', 'directionChangeDistance'],
        'Direction change distance',
        'Distance threshold for path direction changes.',
        0.05,
        METERS,
        0.001,
      ),
      field(
        ['controller', 'mpcConfig', 'motionResolution'],
        'Motion resolution',
        'Reference sampling resolution for MPC.',
        0.05,
        METERS,
        0.001,
      ),
    ],
  },
];
