use super::types::SegmentKind;

pub(super) const PATHS: [&[(SegmentKind, i8)]; 48] = [
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
    ],
    &[
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
        (SegmentKind::Straight, -1),
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
    ],
    &[
        (SegmentKind::Left, -1),
        (SegmentKind::Right, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Left, 1),
        (SegmentKind::Right, -1),
    ],
    &[
        (SegmentKind::Right, -1),
        (SegmentKind::Left, 1),
        (SegmentKind::Straight, 1),
        (SegmentKind::Right, 1),
        (SegmentKind::Left, -1),
    ],
];

pub(super) const PATH_TYPE_INDICES: [(usize, usize, usize, usize); 12] = [
    (0, 1, 2, 3),
    (4, 5, 6, 7),
    (8, 9, 10, 11),
    (12, 13, 14, 15),
    (16, 17, 18, 19),
    (20, 21, 22, 23),
    (24, 25, 26, 27),
    (28, 29, 30, 31),
    (32, 33, 34, 35),
    (36, 37, 38, 39),
    (40, 41, 42, 43),
    (44, 45, 46, 47),
];
